# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MVirdHW8w8gLEMOoh8o40NqsRne9ffca
"""

# Commented out IPython magic to ensure Python compatibility.
# Install kagglehub if not already installed
# %pip install kagglehub

import kagglehub
import os

# Download the latest version of the dataset
dataset_path = kagglehub.dataset_download("vipoooool/new-plant-diseases-dataset")

print(f"Path to dataset files: {dataset_path}")

# List the contents of the downloaded dataset directory
print("Contents of the downloaded dataset:")
for root, dirs, files in os.walk(dataset_path):
    level = root.replace(dataset_path, '').count(os.sep)
    indent = ' ' * 4 * (level)
    print(f'{indent}{os.path.basename(root)}/')
    subindent = ' ' * 4 * (level + 1)
    for f in files:
        print(f'{subindent}{f}')

import matplotlib.pyplot as plt
import os
import random
from PIL import Image

def display_random_images(dataset_root_path, num_images=5):
    """
    Displays a specified number of random images from the dataset.

    Args:
        dataset_root_path (str): The root path of the dataset (e.g., the 'PlantVillage' folder).
        num_images (int): The number of random images to display.
    """
    all_image_paths = []
    for root, _, files in os.walk(dataset_root_path):
        for file in files:
            if file.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp')):
                all_image_paths.append(os.path.join(root, file))

    if not all_image_paths:
        print("No images found in the specified dataset path.")
        return

    selected_images = random.sample(all_image_paths, min(num_images, len(all_image_paths)))

    plt.figure(figsize=(15, 5 * len(selected_images)))
    for i, img_path in enumerate(selected_images):
        try:
            img = Image.open(img_path)
            # Extract label from the parent directory name
            label = os.path.basename(os.path.dirname(img_path))
            if label == 'train' or label == 'val' or label == 'test': # Handle cases where direct parent is train/val/test
                label = os.path.basename(os.path.dirname(os.path.dirname(img_path)))

            plt.subplot(len(selected_images), 3, i*3 + 1) # Adjust subplot layout for better display
            plt.imshow(img)
            plt.title(f"Label: {label}\nFile: {os.path.basename(img_path)}", fontsize=8)
            plt.axis('off')
        except Exception as e:
            print(f"Could not load image {img_path}: {e}")

    plt.tight_layout()
    plt.show()

"""Now, let's try displaying a few random images from the training subset of the dataset. The `dataset_path` variable points to the root of the downloaded dataset."""

import os # Ensure os is imported for path operations

# The dataset_path is '/root/.cache/kagglehub/datasets/vipoooool/new-plant-diseases-dataset/versions/2'
# The 'train' folder is nested inside 'New Plant Diseases Dataset(Augmented)' which is nested again.
train_data_root_path = os.path.join(dataset_path, 'New Plant Diseases Dataset(Augmented)', 'New Plant Diseases Dataset(Augmented)')
train_data_path = os.path.join(train_data_root_path, 'train')

print(f"Attempting to access: {train_data_path}")

if os.path.exists(train_data_path):
    print(f"Path '{train_data_path}' exists. Proceeding to display images.")
    display_random_images(train_data_path, num_images=6)
else:
    print(f"Error: Path '{train_data_path}' does not exist. Please check the dataset structure.")
    # Further debugging for the user if the path still doesn't exist
    print(f"Contents of dataset_path ({dataset_path}): {os.listdir(dataset_path) if os.path.exists(dataset_path) else 'Path does not exist.'}")
    parent_dir_one = os.path.join(dataset_path, 'New Plant Diseases Dataset(Augmented)')
    if os.path.exists(parent_dir_one):
        print(f"Contents of first 'New Plant Diseases Dataset(Augmented)' folder: {os.listdir(parent_dir_one)}")
        parent_dir_two = os.path.join(parent_dir_one, 'New Plant Diseases Dataset(Augmented)')
        if os.path.exists(parent_dir_two):
            print(f"Contents of second 'New Plant Diseases Dataset(Augmented)' folder: {os.listdir(parent_dir_two)}")
            # Check for 'train' directory directly here
            train_check = os.path.join(parent_dir_two, 'train')
            if os.path.exists(train_check):
                print(f"'train' directory found at: {train_check}")

"""## Data Exploration and Feature Extraction

Let's begin by understanding the dataset structure and distribution of classes.
"""

import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Define paths for train, validation, and test datasets
# Re-using train_data_root_path from the previous cell for consistency
valid_data_path = os.path.join(train_data_root_path, 'valid')
test_data_path = os.path.join(dataset_path, 'test', 'test') # The top-level 'test' folder contains another 'test' folder

print(f"Train Data Path: {train_data_path}")
print(f"Validation Data Path: {valid_data_path}")
print(f"Test Data Path: {test_data_path}")

def count_images_and_classes(data_path):
    """
    Counts the number of images and classes in a given dataset path.
    Assumes the structure: data_path/class_name/image.jpg
    """
    class_counts = {}
    for class_name in os.listdir(data_path):
        class_path = os.path.join(data_path, class_name)
        if os.path.isdir(class_path):
            num_images = len([f for f in os.listdir(class_path) if f.lower().endswith(('.png', '.jpg', '.jpeg'))])
            class_counts[class_name] = num_images
    return class_counts

# Get class distribution for the training set
train_class_counts = count_images_and_classes(train_data_path)

# Convert to DataFrame for easier plotting and analysis
train_df = pd.DataFrame(train_class_counts.items(), columns=['Class', 'Count'])

display(train_df.head())

"""### Training Data Class Distribution"""

plt.figure(figsize=(15, 8))
sns.barplot(x='Class', y='Count', data=train_df, palette='viridis')
plt.xticks(rotation=90)
plt.title('Distribution of Plant Disease Classes in Training Set')
plt.xlabel('Plant Disease Class')
plt.ylabel('Number of Images')
plt.tight_layout()
plt.show()

"""### Validation Data Class Distribution"""

# Get class distribution for the validation set
valid_class_counts = count_images_and_classes(valid_data_path)
valid_df = pd.DataFrame(valid_class_counts.items(), columns=['Class', 'Count'])

display(valid_df.head())

plt.figure(figsize=(15, 8))
sns.barplot(x='Class', y='Count', data=valid_df, palette='viridis')
plt.xticks(rotation=90)
plt.title('Distribution of Plant Disease Classes in Validation Set')
plt.xlabel('Plant Disease Class')
plt.ylabel('Number of Images')
plt.tight_layout()
plt.show()

"""### Test Data Class Distribution"""

# Get class distribution for the test set
# The test set images are typically not in class-labeled subdirectories
# Instead, they are directly in the test_data_path
test_image_files = [f for f in os.listdir(test_data_path) if f.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp'))]
total_test_images = len(test_image_files)

# Create a DataFrame to represent the total count
test_df = pd.DataFrame([{'Class': 'Total Test Images (Unlabeled)', 'Count': total_test_images}])

print(f"Total number of test images found: {total_test_images}")
display(test_df) # Display the DataFrame with total count

# Plotting (will show a single bar for total test images)
plt.figure(figsize=(8, 6)) # Adjust figure size for a single bar
sns.barplot(x='Class', y='Count', data=test_df, palette='viridis')
plt.xticks(rotation=45)
plt.title('Total Images in Test Set')
plt.xlabel('') # No specific classes to label
plt.ylabel('Number of Images')
plt.tight_layout()
plt.show()

"""## Data Preparation for Model Training

To prepare the images for training a deep learning model, we'll use `ImageDataGenerator` from TensorFlow/Keras. This will handle:

*   **Rescaling:** Normalizing pixel values to a [0, 1] range.
*   **Image Resizing:** Resizing all images to a consistent size (e.g., 224x224 pixels).
*   **Batching:** Grouping images into batches for efficient model training.
*   **Data Augmentation (for training set):** Applying transformations like rotations, shifts, and flips to the training images to increase the diversity of the training data and improve model generalization.

"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Define image dimensions and batch size
IMG_HEIGHT = 224
IMG_WIDTH = 224
BATCH_SIZE = 32

# Create ImageDataGenerator for training with augmentation
train_datagen = ImageDataGenerator(
    rescale=1./255, # Normalize pixel values to [0, 1]
    rotation_range=40, # Randomly rotate images by up to 40 degrees
    width_shift_range=0.2, # Randomly shift images horizontally
    height_shift_range=0.2, # Randomly shift images vertically
    shear_range=0.2, # Apply shearing transformations
    zoom_range=0.2, # Apply random zoom
    horizontal_flip=True, # Randomly flip images horizontally
    fill_mode='nearest' # Fill new pixels created by transformations
)

# Create ImageDataGenerator for validation and test sets (only rescaling)
validation_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)

print("ImageDataGenerators initialized.")

"""Now, let's create the actual data generators using `flow_from_directory`. These generators will load images from our defined paths, apply the preprocessing steps, and serve them in batches to the model."""

# Create training data generator
train_generator = train_datagen.flow_from_directory(
    train_data_path,
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode='categorical' # For multi-class classification
)

# Create validation data generator
validation_generator = validation_datagen.flow_from_directory(
    valid_data_path,
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode='categorical'
)

# Create test data generator
# For the test set, we need to handle that images are not in subdirectories by class.
# We set class_mode=None and shuffle=False to get predictions in order.
# However, to maintain consistency with `flow_from_directory` and avoid issues with target_size, we'll assume
# the user intends to classify these directly. If labels are needed later, a custom generator might be required.
# For now, let's adapt `flow_from_directory` by pointing it to the folder containing the images directly.
# This will treat each image as its own 'class' effectively for this step if it expects subfolders, or more ideally
# if the test path only contains images, it will generate them without class labels.

# A more robust approach for test data without subfolders:
# test_generator = test_datagen.flow_from_dataframe(
#     dataframe=pd.DataFrame({'filename': test_image_files}), # Assuming test_image_files is a list of filenames
#     directory=test_data_path,
#     x_col='filename',
#     y_col=None,
#     target_size=(IMG_HEIGHT, IMG_WIDTH),
#     batch_size=BATCH_SIZE,
#     class_mode=None,
#     shuffle=False
# )

# Given `test_data_path` points directly to the images, we can use `flow_from_directory` but with a caveat:
# It expects subdirectories. Since the test data doesn't have class subdirectories, we will use `flow_from_directory`
# on the parent folder of `test_data_path` and specify `classes=[os.path.basename(test_data_path)]`.
# This effectively tells it to treat all images within `test_data_path` as one 'class'.

# Determine the parent directory of test_data_path
test_parent_path = os.path.dirname(test_data_path)
test_dir_name = os.path.basename(test_data_path)

# Create test data generator for unlabeled test images
test_generator = test_datagen.flow_from_directory(
    test_parent_path, # Point to the parent directory
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode=None, # No class labels needed for prediction
    shuffle=False, # Keep file order for potential later mapping
    classes=[test_dir_name] # Specify the 'class' as the folder name containing the images
)

print("Data generators created.")
print(f"Number of training samples: {train_generator.samples}")
print(f"Number of validation samples: {validation_generator.samples}")
print(f"Number of test samples: {test_generator.samples}")
print(f"Number of classes: {train_generator.num_classes}")
print(f"Class labels: {train_generator.class_indices}")

"""## Define and Compile the CNN Model

Now, let's define the architecture of our Convolutional Neural Network (CNN). We'll start with a relatively simple sequential model that includes convolutional layers for feature extraction and dense layers for classification. We'll use `tf.keras.applications.MobileNetV2` as a base for transfer learning to leverage pre-trained weights on a large dataset, which usually leads to better performance on image tasks with limited data. This will be adapted for our specific number of classes.
"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import GlobalAveragePooling2D

# Get the number of classes from the training generator
num_classes = train_generator.num_classes

# Load the MobileNetV2 model with pre-trained weights (ImageNet) excluding the top classification layer
base_model = MobileNetV2(input_shape=(IMG_HEIGHT, IMG_WIDTH, 3), include_top=False, weights='imagenet')

# Freeze the base model layers so they are not updated during initial training
base_model.trainable = False

# Create a new model on top of the pre-trained base
model = Sequential([
    base_model,
    GlobalAveragePooling2D(), # Reduces spatial dimensions to a single vector
    Dense(128, activation='relu'), # A dense layer for further feature processing
    Dropout(0.5), # Dropout for regularization
    Dense(num_classes, activation='softmax') # Output layer for classification
])

# Compile the model
model.compile(
    optimizer=Adam(learning_rate=0.0001), # Use a small learning rate for fine-tuning/transfer learning
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

print("CNN model defined and compiled using MobileNetV2 for transfer learning.")
model.summary()

"""## Train the Model

Now we will train the defined CNN model using the `train_generator` and `validation_generator`. We'll also use `EarlyStopping` to stop training when the validation loss stops improving, and `ModelCheckpoint` to save the best model weights during training.
"""

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

# Define callbacks
early_stopping = EarlyStopping(
    monitor='val_loss', # Monitor validation loss
    patience=5, # Number of epochs with no improvement after which training will be stopped
    restore_best_weights=True # Restore model weights from the epoch with the best value of the monitored quantity
)

model_checkpoint = ModelCheckpoint(
    'best_plant_disease_model.keras', # Filepath to save the model
    monitor='val_loss', # Monitor validation loss
    save_best_only=True, # Save only the best model
    mode='min', # The 'best' model has the minimum validation loss
    verbose=1 # Log when model is saved
)

epochs = 20 # You can adjust the number of epochs

history = model.fit(
    train_generator,
    epochs=epochs,
    validation_data=validation_generator,
    callbacks=[early_stopping, model_checkpoint]
)

print("Model training complete.")

# This cell is just a trigger to execute the previous modified cell.
# The actual logic is in cell 7ca61d35.
print("Executing cell 7ca61d35 to analyze test data...")